version: '3'

services:
  dev:
    build:
      context: . 
      dockerfile: Dockerfile
    working_dir: /work
    volumes:
      - ./:/work
      - rust_dev_target:/work/target
    tty: true
    environment:
      CARGO_BUILD_TARGET_DIR: /work/target

volumes:
  rust_dev_target: